import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-arp="">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-emerald-50`}>
        <nav className="sticky top-0 z-50 text-4xl font-display font-bold bg-gray-800 text-emerald-500 p-4">
          Alumnity
        </nav>
        {children}
      </body>
    </html>
  );
}
